### ISSUE TITLE
Release date

### ISSUE THREAD

**Issue by piotrpog** [venveo/craft-characteristic#44]
Hi,
does this plugin have some release date when it will be added to plugin store?

**Comment by Mosnar** [comment]
Hey @piotrpog! Glad you're interested in the plugin! I've been having mixed emotions as to whether or not this plugin should be released publicly. Generally speaking, it works very well; however, in certain cases while applying many filters, the performance will start to degrade sharply to the point of being unusable. The primary cause for this has to do with my decision to use the native Craft relations as the backbone for the system. While it does help in some cases, in other cases it's quite detrimental. My fear is that upon release, many people will start to run into performance issues that can't be resolved without a major overhaul.

Unfortunately, I don't have a lot of time to work on exploring this further right now, but I hope to in the next couple of months. My suggestion is using a proper faceted search tool, such as Algolia or Elastic Search in the mean time.

**Comment by piotrpog** [comment]
Thanks for info!
